plugins {
    id 'java'
    id 'application' 
}

group = 'fr.delversebastien'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    // JDA for Discord API interactions
    implementation "net.dv8tion:JDA:6.4.1"
    // SLF4J Simple for logging, cannot launch without a logging implementation, but can be replaced with another one if needed
    implementation "org.slf4j:slf4j-simple:2.0.7"
    // .env management for loading environment variables from a .env file
    implementation "io.github.cdimascio:dotenv-java:3.0.0"
}

application {
    mainClass = 'fr.delversebastien.bot.Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}