plugins {
    id 'java'
    id 'application' 
}

group = 'fr.delversebastien'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    // JDA for Discord API interactions
    implementation "net.dv8tion:JDA:6.4.1"
    // SLF4J Simple for logging, cannot launch without a logging implementation, but can be replaced with another one if needed
    implementation "org.slf4j:slf4j-simple:2.0.7"
    // .env management for loading environment variables from a .env file
    implementation "io.github.cdimascio:dotenv-java:3.0.0"
    // JSON manipulation library
    implementation 'org.json:json:20231013'
}

application {
    mainClass = 'fr.delversebastien.bot.Main'
}

// You shall endure agony if you use any other version that is not Java 21,
// because JDA is not compatible with it, 
// and you will have a bad time trying to make it work (like I did, trust me, I know what I'm talking about), 
// so we will use Java 21 which is the latest LTS version and is compatible with JDA, 
// and also has some nice features that we can use in our code, so it's a win-win situation for everyone.

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('wrapper') {
    gradleVersion = '9.5.0'
    distributionType = Wrapper.DistributionType.ALL
}